lab12/config/routes.rb
Rails.application.routes.draw do
  match 'auth/register', via: %i[post get], as: :register
  match 'auth/login', via: %i[post get], as: :login
  get 'auth/logout', as: :logout
  resources :users
  get 'welcome/index'
  get 'welcome/result'
  post 'welcome/result'
  get 'welcome/cached'

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

lab12/app/models/cached_result.rb
# frozen_string_literal: true

require 'bencode'

class CachedResult < ApplicationRecord
  validates :n, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, uniqueness: true
  validates :result, presence: true, format: { with: /l(i\d+e)+e/, message: '%<value>s is not valid list of integers' }

  def values
    BEncode.load(self[:result])
        .each_slice(2)
        .map { |x| { x: x[0], xsqr: x[1] } }
        .to_a
  end

  def values=(values)
    self[:result] = values.map { |res| [res[:x], res[:xsqr]] }
                        .flatten
                        .bencode
  end
end

lab12/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_auth

  protected

  def auth_verifier
    Rails.application.message_verifier('auth')
  end

  def fetch_current_user
    cookie_id = cookies[:user_id]
    id = auth_verifier.verified(cookie_id, purpose: :auth)
    user = User.find_by(id: id)
    @current_user = user
  end

  def require_auth
    fetch_current_user
    redirect_to login_path unless @current_user
  end
end

lab12/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:login, :password)
  end
end

lab12/app/helpers/users_helper.rb
module UsersHelper
end

lab12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header style="display: flex">
  My Site
  <% if @current_user %>
    <div style="display: inline-block; margin-left: auto">
      Hi, <%= @current_user.login %>. <%= link_to :Logout, logout_path %>
    </div>
  <% end %>
</header>
<div>

  <%= yield %>
</div>
</body>
</html>

lab12/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user and user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab12/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'users/form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

lab12/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Password</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= '*' * 5 %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

lab12/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'users/form', user: @user %>

<%= link_to 'Back', users_path %>

lab12/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Password:</strong>
  <%= '*' * 10 %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

lab12/app/views/welcome/index.html.erb
<h1>Palndrome machine</h1>

<%= form_with id: :form, format: :json, url: welcome_result_path, method: 'get' do |f| %>
<%= f.label :n, :N %>
<%= f.number_field :n, required: true, min: 1, value: '5' %>

<%= f.submit 'Посчитать' %>
<% end %>

<div id="result"></div>

<%= javascript_pack_tag 'welcome' %>

lab12/app/views/welcome/result.html.erb
<h1>Palndrome machine</h1>
<style>
    tr>* {
        text-align: right;
    }
</style>

<table>
    <tr>
    </tr>
    <% @result.each { |row| %>
    <tr>
        <td><%= row[:x] %></td>
        <td><%= row[:xsqr] %></td>
    </tr>
    <% } %>
    <tr>
        <td>Count:</td>
        <td><strong><%= @result.size-1 %></strong></td>
    </tr>
</table>